t-shirts test added
cristiancobo/cypress-training pull request #4
Opened 2022-05-27 19:48 UTC by cristiancobo

2022-05-27 22:35 UTC, holgiosalos requested changes
run the `lint:fix` command, also, fix the EOF in all the files that you see this warning:
![image](https://user-images.githubusercontent.com/10209180/170796832-b523649c-f3ce-4417-9f6f-048deeac1e81.png)

nice to see the usage of `Cypress.env`

2022-05-31 13:43 UTC, manuelq12 requested changes

2022-05-31 13:43 UTC, manuelq12 commented on cypress.json
> +
You don't need this blank spaces for the EOF, just one is okay

2022-05-31 13:43 UTC, manuelq12 commented on cypress/page/address/address.page.ts
> +
Please erase this blank space, just be sure the EOF is there

2022-05-31 13:43 UTC, manuelq12 commented on cypress/page/authentication/authentication.page.ts
> +
Please erase this blank space, just be sure the EOF is there

2022-05-31 13:43 UTC, manuelq12 commented on cypress/page/t-shirts/t-shirts.page.ts
> +
Blank space and also EOF

2022-05-31 14:12 UTC, manuelq12 commented on cypress/page/index.ts
> +
Why so many blank spaces?

2022-05-31 18:18 UTC, holgiosalos approved these changes

2022-05-31 18:18 UTC, holgiosalos commented on cypress/page/t-shirts/t-shirts.page.ts
> +  }
Fix the indentation for next PR

2022-05-31 18:18 UTC, manuelq12 approved these changes

2022-05-31 20:50 UTC, merged