Develop
cristiancobo/cypress-training pull request #6
Opened 2022-06-01 19:26 UTC by cristiancobo

2022-06-03 13:26 UTC, holgiosalos commented on cypress/page/t-shirts/t-shirts.page.ts
> +
remove this blank line

2022-06-03 13:26 UTC, holgiosalos commented on cypress/page/t-shirts/t-shirts.page.ts
> +
remove this blank line

2022-06-03 13:26 UTC, holgiosalos commented on cypress/page/t-shirts/t-shirts.page.ts
>          .get(this.addToCartButton)
we can avoid this if you use again filter or find method using the addToCartButton selector

2022-06-03 13:26 UTC, holgiosalos commented on cypress/page/t-shirts/t-shirts.page.ts
> +
remove this blank lines

2022-06-03 21:41 UTC, manuelq12 requested changes
@cristiancobo Hey cris, the idea of placing the information on the Cypress.json, but as they are global variables is not the right place to put them. If you would like to go with this approach you need to place this information on the "fixtures" folder

Here is some documentation, if you haven't erased the examples that cypress loads when you install it you can check what i mean
https://docs.cypress.io/api/commands/fixture

2022-06-07 18:03 UTC, manuelq12 commented
@cristiancobo Hey, can you add the mochawesome report please?

2022-06-07 18:11 UTC, cristiancobo commented
> @cristiancobo Hey, can you add the mochawesome report please?
@manuelq12 Report is in the commit

2022-06-07 19:47 UTC, manuelq12 approved these changes

2022-06-07 22:02 UTC, merged